name: Build

# Run this workflow every time a new commit pushed to your repository
on: [push, pull_request]

jobs:
  setup:
    name: Install zig and gyro
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - uses: mattnite/setup-gyro@v1
  system:
    name: Link to system SDL
    needs: setup
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - run: gyro build -Dlink=system

  local:
    name: Link to locally built SDL
    needs: setup
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        link: [static, shared]
    steps:
      - run: gyro build -Dlink=${{ matrix.link }}
