name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  system:
    name: Link to system SDL
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - uses: mattnite/setup-gyro@v1.0.0
      - uses: actions/checkout@v2
      - run: gyro build -Dlink=system

  local:
    name: Link to locally built SDL
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        link: [static, shared]
    steps:
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - uses: mattnite/setup-gyro@v1.0.0
      - uses: actions/checkout@v2
      - run: gyro build -Dlink=${{ matrix.link }}
